# Generated by Django 4.0.5 on 2023-06-08 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('C_Id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=100)),
                ('C_Email', models.CharField(max_length=200)),
                ('C_Number', models.IntegerField()),
                ('C_Dob', models.DateField(null=True)),
                ('C_Yoe', models.IntegerField()),
                ('C_JobTitles', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('R_Id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('R_Name', models.CharField(max_length=100)),
                ('R_UserName', models.CharField(max_length=50, unique=True)),
                ('R_Password', models.CharField(max_length=50)),
            ],
        ),
    ]
