# Generated by Django 4.0.5 on 2023-06-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_DOS', models.DateField(auto_now=True)),
                ('S_ConsultantJobTitle', models.CharField(max_length=100)),
                ('S_ImplementationPartner', models.CharField(max_length=100)),
                ('S_EndClient', models.CharField(max_length=100)),
                ('S_EndClientLocation', models.CharField(max_length=150)),
                ('S_ImplementationPartner_Name', models.CharField(max_length=100)),
                ('S_ImplementationPartner_Contact', models.IntegerField()),
                ('S_ConsultantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp1.recruiter')),
            ],
        ),
    ]
