# Generated by Django 4.0.5 on 2023-06-08 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0002_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='C_Email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='C_Id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='S_DOS',
            field=models.DateField(auto_now_add=True),
        ),
    ]
