# Generated by Django 4.0.5 on 2023-06-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0003_alter_consultant_c_email_alter_consultant_c_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='S_ConsultantId',
            new_name='S_RecruiterId',
        ),
    ]
