# Generated by Django 4.0.5 on 2023-06-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0004_rename_s_consultantid_submissions_s_recruiterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='S_ConsultantId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp1.consultant'),
        ),
    ]
