# Generated by Django 4.0.5 on 2023-06-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0006_recruiter_is_active_recruiter_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='R_Password',
        ),
    ]
